### ISSUE TITLE
KiCAD library

### ISSUE THREAD

**Issue by SoulEst** [NextThingCo/CHIP_Pro-Hardware#5]
Thank you very much for supplying the footprint file for EAGLE. As my colleagues and I are use KiCAD for our work, we need a KiCAD library for the CHIP Pro.

**Comment by Flexshot** [comment]
A footprint for multiple EDA packages including KiCad has been uploaded.

**Comment by nevercast** [comment]
I believe this issue should be reopened unless NextThingCo wishes to state that they do not wish to support/maintain footprints/parts for multiple EDA packages.

It would be nice to know NextThingCo's plan regarding this (since the files have since been removed from master). Do I wait for support, or do I go about converting the EAGLE files?

Thanks.

**Comment by wesleycha** [comment]
The old library (that was deleted) does not work with the latest KiCad version. Thus, there is no useable KiCad library for CHIP Pro. I agree that this should be reopened.

**Comment by alleybeachelectric** [comment]
The footprint is available in PDF format. I have created the footprint in EAGLE 8.x without any problems.

If you are having difficulties making the part in KiCad, I would recommend using a third party to design the component such as SnapEDA. Last I recall though, there is a footprint and symbol for CHIP_Pro already over there.
